ALTER TABLE "StampCards" ADD COLUMN IF NOT EXISTS "CreatedBy" TEXT;
ALTER TABLE "StampCards" ADD COLUMN IF NOT EXISTS "UpdatedBy" TEXT;
ALTER TABLE "StampCards" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "StampCards" ADD COLUMN IF NOT EXISTS "DeletedAt" TIMESTAMP;
ALTER TABLE "StampCards" ADD COLUMN IF NOT EXISTS "DeletedBy" TEXT;

